### ISSUE TITLE
Forbidden: You don't have permission to access this resource.

### ISSUE THREAD

**Issue by deanfourie1** [24eme/signaturepdf#138]
When attempting to access the web server, I get this error.

Forbidden
You don't have permission to access this resource.

Apache/2.4.62 (Debian) Server at 172.16.101.7 Port 8084

Any ideas?

Thanks

**Comment by deanfourie1** [comment]
just a simple install with docker-compose,

But I found my error. my Server IP address had changed a while ago and I forgot to update the docker compose file.

```
version: "3.3"
services:
  signaturepdf:
    restart: always
    container_name: signaturepdf
    ports:
      - 8084:80
    environment:
      - SERVERNAME=192.168.1.100:8084
      - UPLOAD_MAX_FILESIZE=48M
      - POST_MAX_SIZE=48M
      - MAX_FILE_UPLOADS=401
      - PDF_STORAGE_PATH=/data
    image: signaturepdf
networks: {}
```

Thank you anyway!
